### PR TITLE
Fix: use values instead of itervalues and extract parser from class b…

### PR DESCRIPTION
**Pull request by Navega**
…ecause "self" isn't used for it.

### CODE REVIEW

**Review by pablodiazgutierrez — APPROVED** [review]

**Review by kharenzze — COMMENTED** [review]
Looks good

**Review by kharenzze — COMMENTED** [review]
👍

**Comment by kharenzze** [comment]
I cannot find the 'approve' button. Maybe because it's already merged

**Comment by pablodiazgutierrez** [comment]
Likely, yes.

**Pull request merged**
